### ISSUE TITLE
pymgclient build/import issue

### ISSUE THREAD

**Issue by stevemarin** [memgraph/pymgclient#22]
I'm running memgraph-mage in a docker container and building pymgclient in another.  The build process goes fine, but when I try to import pymgclient, I get an error that seems to have something to do with SSL, but I'm not quite sure.

```
import mgclient
ImportError: .../python3.9/site-packages/mgclient.cpython-39-x86_64-linux-gnu.so: undefined symbol: EVP_PKEY_base_id
```

Any ideas?

**Comment by antaljanosbenjamin** [comment]
Hi @stevemarin!

I think the issue is pymgclient is built using an older version of OpenSSL than the other machine has. If you check [this commit](https://github.com/openssl/openssl/commit/ed576acdf591d4164905ab98e89ca5a3b99d90ab#diff-7be17a378707cd24bee6dd38b4f7da3b702397cf75364305fe31bdde486fb998R973) from OpenSSL you will see it was renamed ~5 months ago (check in `crypto/evp/p_lib.c`). My first suggestion would be try to build pymgclient on the same machine as you are going to use it. If it is not possible, then try to sync the OpenSSL versions between the docker images. That way you should be able to transfer the built binaries.

**Comment by katarinasupe** [comment]
Cleaning up a bit... @stevemarin can this issue be closed? Btw. I know a bunch of time passed by, but did you end up using Memgraph?

**Comment by katarinasupe** [comment]
Thank you for the quick response 😄 If you want to stay in touch, feel free to [join our Discord community](https://www.discord.gg/memgraph) and let us know when you get back to your project :) By the way, what was your graph use case?
